### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by acathers** [Together-Java/TjBot#7]
```
import org.togetherjava.discordbot.cli.CliArgumentSpecification_Parser;
````
import in BotMain.java is not valid, missing java file.

**Comment by Luminiscental** [comment]
Maybe a more complete guide to setting up the code base for development in CONTRIBUTING.md would be desirable.

**Comment by AzatothTheAwakened** [comment]
The used class is generated while compiling with maven.
The issue was fixed by running `mvn compile` before starting the bot inside an IDE.
